name: RuboCop

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Run RuboCop linter
      uses: reviewdog/action-rubocop@v2.14.0
      with:
        github_token: ${{ secrets.github_token }}
        rubocop_flags: -DES
        rubocop_version: gemfile
        rubocop_extensions: rubocop-performance:gemfile rubocop-rails:gemfile
        level: warning
